services:
  api:
    container_name: tiny_url_api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile

  postgres:
    image: postgres:latest
    container_name: tiny_url_database
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./data/.env
    volumes:
      - db:/var/lib/postgresql/data/
      - ./data/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
